### ISSUE TITLE
WebApp not showing brave browser 

### ISSUE THREAD

**Issue by ashishlotake** [linuxmint/webapp-manager#192]
I am not able to use/select brave browser in "BROWSERS". It not showing brave browser, firefox,edge,chrom all are their. But not brave

**Comment by Bewbman** [comment]
Hey can confirm I am having same issue here, Brave Browser does not show in WebApps as an option despite being my default browser. Thanks

**Comment by ashishlotake** [comment]
Other Chromium based browser works fine. Seem its issue with BRAVE. I tried edge and it works fine.

**Comment by beevabeeva** [comment]
Hi, having a similar issue with Firefox after updating to Ubuntu 22 from 21.

Installing firefox (without removing current install) with apt, gets webapp-manager to show firefox as an option.

However, when launching the app it does not work (error: firefox instance is already running...)

Looking at the terminal output when launching the app from webapp-manager there is error:
![image](https://user-images.githubusercontent.com/19332617/185883228-617cd8a4-18c5-48c5-959c-dc41146babc8.png)

Will open a separate issue after going through a few more current ones first.

**Comment by beevabeeva** [comment]
Update: my problem described above is a different problem.
Brave works fine for me in terms of showing up in the list of browsers.

If anyone is having issues getting firefox to work with webapp-manager it's probably because the latest version of firefox no longer supports webapps. 

## Wrokaround:

I installed the last version of firefox known to support webapps (96- build2) **alongside** the latest version (104).
Following the instructions from user Flemur (link: https://forums.linuxmint.com/viewtopic.php?t=318597)
![image](https://user-images.githubusercontent.com/19332617/187073594-429bfa36-f144-4d31-ab5b-b61b0c156b7c.png)

And editing the `.desktop` file created by webapp-manager to use `firefox96` instead of `firefox`, to look like this:
![image](https://user-images.githubusercontent.com/19332617/187073689-b1cc06e2-0357-4844-90c2-528ad25ebc57.png)

You can locate the path of the .desktop file by starting webapp-manager from the terminal and launching the app you intend to edit.

Now everything should work again!

I will make an issue for this, then close it, to act as a reference for anyone else.

**Comment by dazzat1960** [comment]
I thought I had fixed this by adding brave to the common.py but even though brave is now listed it does not work.

**Comment by aaronmurniadi** [comment]
> I thought I had fixed this by adding brave to the common.py but even though brave is now listed it does not work.

Have you tried creating a symbolic link from wherever your brave binary is to `/usr/bin/brave` ?

```
$ ln /usr/bin/brave-browser /usr/bin/brave
```

If it works, consider supporting my PR at #209 

Good luck!

**Comment by kernelcrunch** [comment]
> ln /usr/bin/brave-browser /usr/bin/brave

This symbolic link worked quick and simple for me.  Thanks!
