### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by mfreeman72** [linuxmint/webapp-manager#21]
I've installed the beta version linked from Clem's August 2020 blog post. When I try to run it, nothing happens. In a terminal, I get the following output:

Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 51, in activate
    window = WebAppManagerWindow(self)
  File "/usr/lib/webapp-manager/webapp-manager.py", line 196, in __init__
    self.load_webapps()
  File "/usr/lib/webapp-manager/webapp-manager.py", line 444, in load_webapps
    webapps = self.manager.get_webapps()
  File "/usr/lib/webapp-manager/common.py", line 102, in get_webapps
    webapp = WebAppLauncher(path)
  File "/usr/lib/webapp-manager/common.py", line 52, in __init__
    for line in desktop_file:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 116: invalid start byte

This is on Linux Mint 20 Cinnamon.

**Comment by gadass** [comment]
I was finding a similar issue "UnicodeDecodeError: 'utf-8' codec can't decode byte".

After some research, this seems to be several causes for this error. In my case, was because of software conflicts.  

Try to log in with a new user account and run the web app. If works should be a particular software in your default user that seems to conflict with the web apps-manager.

**Comment by mfreeman72** [comment]
I created a new user account, and webapp-manager worked. So on my original user account, I removed all .hidden files and relogged in. Webapp-manager worked there. I reconstructed all of my settings, relogged in, and webapp-manager still worked. Then I rebooted. Now it doesn't work again. Same traceback error as before. I have no idea what's specifically causing this.

**Comment by gadass** [comment]
wow... you have taken a drastic step to solving this. Try to decompose your steps in order to find the conflicting software. Instead to remove the folders, only rename them. For example, rename only the .local  as local-backup, relog and try to use the web app again. If works, return the original .local files one per time. You should be able to find this conflicting software somewhere. Note that you can also do this with .config folder.
