### ISSUE TITLE
Credentials data is not saved

### ISSUE THREAD

**Issue by murkl** [linuxmint/webapp-manager#284]
Unfortunately, the credetial data is not saved. I use ungoogled-chromium (no flatpak). 
After closing the window and open again, i have to login again.
I am on Arch Linux

Edit: Same with the ungoogled-chromium Flatpak version, with Firefox (native) and Chromium (native) it works.

**Comment by MeatImp** [comment]
What site are you using? 
Have you allowed cookies from this site?

perhaps this is a site-exclusive issue

**Comment by murkl** [comment]
I tryed https://web.webex.com but this issue occurs with all websites. I have allowed cookies.

It seems that is a ungoogled chromium issue, with chromium & firefox (native or flatpak) it works.

**Comment by MeatImp** [comment]
In the spirit of helping, could you check if the profile created for your webapp saves information on your drive? chromium is 

What I mean is that the web-app manager creates a profile in order to keep separate information. You can check this by checking which command runs from the shortcut created but the web-app manager. This is an example from my duolingo app. 

`sh -c 'XAPP_FORCE_GTKWINDOW_ICON="web-duolingo" firefox --class WebApp-Duolingo3024 --name WebApp-Duolingo3024 --profile /home/usr/.local/share/ice/firefox/Duolingo3024 --no-remote "http://duolingo.com"'`

going to /home/usr/.local/share/ice/firefox/Duolingo3024 we can check the contents of the created profile. Perhaps you could run a ls command we could check if these directories are being created correctly. My intuition is that these profiles might no be created correctly with your browser of choice.

**Comment by murkl** [comment]
It's confusing. I just wanted to try it again with ungoogled chromium and see if the data is backed up and it seems to work now. Thanks for your support!
