### ISSUE TITLE
Add support for Chromium (snap)

### ISSUE THREAD

**Issue by mwoz123** [linuxmint/webapp-manager#71]
First of all thanks for the great app:)
I've been looking forward to it for a long time;)

Is there a possibility to add Chromium (installed from Snapcraft) option in browser dropdown?

**Comment by Coeur-Noir** [comment]
It's there, when using Ubuntu distros ( official, budgie, and so on ).
Mint _might_ do something different regarding snap/snapd though.

+ you may look at https://github.com/linuxmint/webapp-manager/issues/51#

**Comment by mwoz123** [comment]
I'm using latest chromium from snap repo:
```
marcin@pc:~/workspace/webapp-manager$ snap list | grep chromium
chromium                         87.0.4280.141               1444   latest/stable    canonical*       -
chromium-ffmpeg                  0.1                         17     latest/stable    canonical*       -
marcin@pc:~/workspace/webapp-manager$ 
```

Executable located in: `/snap/bin/chromium` : 
```
marcin@pc:~/workspace/webapp-manager$ whereis chromium
chromium: /etc/chromium /snap/bin/chromium.chromedriver /snap/bin/chromium
marcin@pc:~/workspace/webapp-manager$ 
```
Just to confirm I'm on ubuntu:
```
marcin@pc:~/workspace/webapp-manager$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
marcin@pc:~/workspace/webapp-manager$ 
```

And I've only firefox in dropdown:

![Screenshot from 2021-01-19 22-54-47](https://user-images.githubusercontent.com/4487025/105097804-7db63c80-5aa9-11eb-8483-955943130aef.png)

**Comment by mwoz123** [comment]
I did hacked/added  :
common.py:
+ `browsers.append(Browser(BROWSER_TYPE_CHROMIUM, "Chromium (Snap)", "chromium", "/snap/bin/chromium"))`

and now I've:
![Screenshot from 2021-01-19 23-02-25](https://user-images.githubusercontent.com/4487025/105098488-6fb4eb80-5aaa-11eb-8c4e-5907660a1ade.png)
will create PR for it

**Comment by Coeur-Noir** [comment]
How did you install Chromium ?

Was it by
`sudo apt install chromium-browser`
or
`snap install chromium`
?

First is a transitional .deb package that actually installs the snap, which probably creates needed legacy links and paths whereas the latter only does things at snap level ?

**Comment by mwoz123** [comment]
I did `sudo snap install chromium`

I don't have that transitional package installed: 
```
marcin@pc:~/workspace/webapp-manager$ apt -qq list chromium-browser
chromium-browser/focal 80.0.3987.163-0ubuntu1 amd64
```

**Comment by Coeur-Noir** [comment]
Maybe install it and see if that makes web-app-manager « aware » of chromium-snap ?

**Comment by mwoz123** [comment]
But let's do a step back. 

Does 
> sudo **apt install** <package_name  here 'chromium-browser'>` ?

is a (preferred) way to install **snap** package? 

What with non-deb distros that does support snap but doesn't have this "transitional deb package"?

I did install and it does add another entry in webapp-manger 
but IMHO it's not "aware" of chromium snap but rather chromium deb package.

**Comment by Coeur-Noir** [comment]
Totally, I guess that transitional package provided by Canonical in *buntu's distributions probably installs symlinks in legacy folders, therefore enabling WebAppManager to « find » Chromium browser _as if_ it was installed as a _.deb_.

You are right it's a problem outside Ubuntu's realm.

_is a (preferred/any?) way to install any snap package?_
_Snapstore_ is the only source for _any_ snap. Here Chromium in Ubuntu is a peculiar case since it is no longer available as a _.deb_ from official Ubuntu APT repositories ( since Ubuntu v19.10 I think ). Hence that _.deb_ transitional package for providing a way to install Chromium using the legacy APT route.

So only way to fix this is making WebAppManager
+ able to see if any web-browsers are installed as snap and to be found in `~/snap/…` or also in `/snap` or `/var/snap`
+ if internet-browser = snap, then use a path for ICE profile _this_ snap can reach, most of the time inside `~/snap/internet-browser/{common|.cache|else_maybe}` or even just in '~/snap/ice' might be enough ( easier, and unaffected by further modifications regarding snap management by user ).

A snap app will access basically to '~/snap' and **non-hidden** files and folders in '/home/$USER' and if connected to _removable-media_ interface also to '/media', '/mnt' and '/run/media'. Nowhere else. That's why Chromium as a snap can't access to `~/.config/chromium` or '~/.local/share/ice'.

https://snapcraft.io/docs/interface-management

**Comment by mwoz123** [comment]
> A snap app will access basically to ~/snap and non-hidden files and folders in /home/$USER and if connected to removable-media interface also to /media, /mnt and /run/media. Nowhere else. That's why Chromium as a snap can't access to ~/.config/chromium or ~/.local/share/ice.

you're right I didn't spot it's trying to config/icon files outside ~/snap. 

> So only way to fix this is making WebAppManager

ok.. as I hardly know python, feel free to takeover or reject the PR https://github.com/linuxmint/webapp-manager/pull/72

**Comment by candrapersada** [comment]
support for Chromium (flatpak)?

**Comment by mwoz123** [comment]
> support for Chromium (flatpak)?

As far as I see:
https://github.com/linuxmint/webapp-manager/blob/master/usr/lib/webapp-manager/common.py#L141

 it supports [lighter version of chromium](https://flathub.org/apps/details/com.github.Eloston.UngoogledChromium)

@candrapersada - Anyway to not create a mess in tickets I think your FR should be in separate ticket/issue.

**Comment by Coeur-Noir** [comment]
> ok.. as I hardly know python, feel free to takeover or reject the PR #72

Well am just an old basic user who tries to understand how things work. I have zero skill in code to comment your PR.

I happen to use peppermint's ICE for a couple of years in my *buntu's where all these « flaws » regarding chromium-snap had already been pointed, see https://github.com/peppermintos/ice/issues/47
